"""Compile the tuned GEMM tables into the library.

    gemm_table.py --tuning-dir kernels/rocm/tuning --archs gfx1201[,...] --out <build>/gemm_tuned_table.inc

Reads <tuning-dir>/<arch>/gemm.tsv for every build architecture that has one (written by the GEMM
tuner, tools/gemm_tune.cpp) and writes the rows as C++ initialisers of turbine_hip::TunedGemm
(src/gemm_table.hpp). A malformed row fails the build. Columns (tab-separated, `#` comments):
n, k, trans_b, c_dtype (bf16|f32), m_max, solution_index, solution_name (or -1 and `heuristic`:
the bucket keeps hipBLASLt's first heuristic answer per call), then informational columns the
library ignores.
"""

import argparse
import pathlib
import re
import sys

DTYPES = {"bf16": 0, "f32": 2}  # TURBINE_DTYPE_BF16, TURBINE_DTYPE_F32
NAME = re.compile(r"^[A-Za-z0-9_]+$")
# A bucket where no solution beat hipBLASLt's own per-call answer (index -1).
HEURISTIC = "heuristic"


def rows(path: pathlib.Path):
    with path.open() as f:
        for lineno, line in enumerate(f, 1):
            line = line.rstrip("\n")
            if not line.strip() or line.startswith("#"):
                continue
            cols = line.split("\t")
            where = f"{path}:{lineno}"
            if len(cols) < 7:
                sys.exit(
                    f"{where}: expected at least 7 tab-separated columns, got {len(cols)}"
                )
            try:
                n, k, trans_b, m_max, index = (int(cols[i]) for i in (0, 1, 2, 4, 5))
            except ValueError as e:
                sys.exit(f"{where}: {e}")
            if cols[3] not in DTYPES:
                sys.exit(f"{where}: c_dtype {cols[3]!r} is not one of {sorted(DTYPES)}")
            if n <= 0 or k <= 0 or m_max <= 0 or trans_b not in (0, 1):
                sys.exit(f"{where}: n, k, m_max must be positive, trans_b 0 or 1")
            if (cols[6] == HEURISTIC) != (index == -1) or index < -1:
                sys.exit(
                    f"{where}: index -1 goes with the name {HEURISTIC!r}, else index >= 0"
                )
            if not NAME.match(cols[6]):
                sys.exit(
                    f"{where}: solution name {cols[6]!r} is not a hipBLASLt solution name"
                )
            yield n, k, trans_b, DTYPES[cols[3]], m_max, index, cols[6]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tuning-dir", required=True, type=pathlib.Path)
    ap.add_argument("--archs", required=True)
    ap.add_argument("--out", required=True, type=pathlib.Path)
    args = ap.parse_args()
    out = ["// Generated by kernels/rocm/cmake/gemm_table.py; do not edit."]
    for arch in [a for a in args.archs.replace(";", ",").split(",") if a]:
        path = args.tuning_dir / arch / "gemm.tsv"
        if not path.exists():
            out.append(
                f"// {arch}: no {path.name}; every GEMM runs the heuristic's choice"
            )
            continue
        seen = set()
        for n, k, trans_b, c_dtype, m_max, index, name in rows(path):
            key = (n, k, trans_b, c_dtype, m_max)
            if key in seen:
                sys.exit(
                    f"{path}: duplicate row for n={n} k={k} trans_b={trans_b} m_max={m_max}"
                )
            seen.add(key)
            out.append(
                f'{{"{arch}", {n}, {k}, {trans_b}, {c_dtype}, {m_max}, {index}, "{name}"}},'
            )
    text = "\n".join(out) + "\n"
    if not args.out.exists() or args.out.read_text() != text:
        args.out.write_text(text)


if __name__ == "__main__":
    main()
