// The tuned GEMM algorithm table (gemm_table.hpp): lookup and resolution.
#include <hipblaslt/hipblaslt-ext.hpp>

#include <exception>
#include <string>
#include <vector>

#include "gemm_table.hpp"
#include "turbine_hip.hpp"

namespace {

// Generated by cmake/gemm_table.py from kernels/rocm/tuning/<arch>/gemm.tsv
// for every build architecture that has one.
const turbine_hip::TunedGemm kTable[] = {
#include "gemm_tuned_table.inc"
    {nullptr, 0, 0, 0, 0, 0, 0, nullptr},
};

// The solution index of name for output type c_dtype in this hipBLASLt, or -1
// (the whole solution list is read once per context and output type).
int index_by_name(turbine_ctx *ctx, int32_t c_dtype, const std::string &name) {
  auto &names = ctx->gemm_solutions[c_dtype];
  if (names.empty()) {
    const hipDataType c = turbine_hip::gemm_out_type(c_dtype);
    std::vector<hipblasLtMatmulHeuristicResult_t> all;
    // Every Turbine GEMM has the weight transposed or not; list both.
    for (hipblasOperation_t op : {HIPBLAS_OP_T, HIPBLAS_OP_N}) {
      all.clear();
      if (hipblaslt_ext::getAllAlgos(
              ctx->blaslt, hipblaslt_ext::GemmType::HIPBLASLT_GEMM, op,
              HIPBLAS_OP_N, HIP_R_16BF, HIP_R_16BF, c, c, HIPBLAS_COMPUTE_32F,
              all) != HIPBLAS_STATUS_SUCCESS) {
        continue;
      }
      for (auto &r : all) {
        names.emplace(
            hipblaslt_ext::getSolutionNameFromAlgo(ctx->blaslt, r.algo),
            hipblaslt_ext::getIndexFromAlgo(r.algo));
      }
    }
    // A marker so a failed listing is not repeated for every call.
    names.emplace("", -1);
  }
  const auto found = names.find(name);
  return found == names.end() ? -1 : found->second;
}

// The algorithm of solution index, when this hipBLASLt has it and it carries
// name.
bool algo_at(turbine_ctx *ctx, int index, const char *name,
             hipblasLtMatmulAlgo_t *algo) {
  if (index < 0)
    return false;
  std::vector<int> indices{index};
  std::vector<hipblasLtMatmulHeuristicResult_t> found;
  if (hipblaslt_ext::getAlgosFromIndex(ctx->blaslt, indices, found) !=
          HIPBLAS_STATUS_SUCCESS ||
      found.empty()) {
    return false;
  }
  if (hipblaslt_ext::getSolutionNameFromAlgo(ctx->blaslt, found[0].algo) !=
      name)
    return false;
  *algo = found[0].algo;
  return true;
}

} // namespace

namespace turbine_hip {

const TunedGemm *tuned_gemm(const std::string &arch, const GemmShape &s) {
  const TunedGemm *serving = nullptr;
  const TunedGemm *largest = nullptr;
  for (const TunedGemm *t = kTable; t->arch != nullptr; ++t) {
    if (arch != t->arch || t->n != s.n || t->k != s.k ||
        t->trans_b != s.trans_b || t->c_dtype != s.c_dtype) {
      continue;
    }
    if (t->m_max >= s.m && (serving == nullptr || t->m_max < serving->m_max))
      serving = t;
    if (largest == nullptr || t->m_max > largest->m_max)
      largest = t;
  }
  return serving != nullptr ? serving : largest;
}

const char *tuned_gemm_miss_code(TunedGemmMiss miss) {
  switch (miss) {
  case TunedGemmMiss::Unavailable:
    return "gemm_table_unavailable";
  case TunedGemmMiss::Unsupported:
    return "gemm_table_unsupported";
  }
  return "gemm_table_unknown";
}

hipblasStatus_t pinned_gemm(turbine_ctx *ctx, GemmProblem &p,
                            const turbine_gemm_desc *d,
                            hipblasLtMatmulAlgo_t *algo, bool run) {
  try {
    hipblaslt_ext::Gemm gemm(ctx->blaslt, p.desc.handle, &d->alpha, d->b,
                             p.weight.handle, d->a, p.act.handle, &d->beta,
                             d->c, p.out.handle, d->c, p.out.handle);
    hipblaslt_ext::GemmTuning tuning;
    tuning.setSplitK(1);
    gemm.setMaxWorkspaceBytes(kGemmWorkspaceBytes);
    if (!run) {
      size_t workspace = 0;
      const hipblasStatus_t st = gemm.isAlgoSupported(*algo, tuning, workspace);
      if (st != HIPBLAS_STATUS_SUCCESS)
        return st;
      return workspace > kGemmWorkspaceBytes ? HIPBLAS_STATUS_NOT_SUPPORTED
                                             : HIPBLAS_STATUS_SUCCESS;
    }
    const hipblasStatus_t st =
        gemm.initialize(*algo, tuning, ctx->workspace, false, ctx->stream);
    if (st != HIPBLAS_STATUS_SUCCESS)
      return st;
    return gemm.run(ctx->stream);
  } catch (const std::exception &) {
    return HIPBLAS_STATUS_INTERNAL_ERROR;
  }
}

bool resolve_tuned_gemm(turbine_ctx *ctx, const TunedGemm &t, GemmProblem &p,
                        const turbine_gemm_desc *d, hipblasLtMatmulAlgo_t *algo,
                        TunedGemmMiss *miss) {
  // The pinned index first; when this hipBLASLt numbers its solutions
  // differently, the solution of the same name wherever it now is.
  if (!algo_at(ctx, t.solution_index, t.solution_name, algo) &&
      !algo_at(ctx, index_by_name(ctx, t.c_dtype, t.solution_name),
               t.solution_name, algo)) {
    *miss = TunedGemmMiss::Unavailable;
    return false;
  }
  if (pinned_gemm(ctx, p, d, algo, false) != HIPBLAS_STATUS_SUCCESS) {
    *miss = TunedGemmMiss::Unsupported;
    return false;
  }
  return true;
}

} // namespace turbine_hip
